/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.avaliacao.sprint1;

import javafx.scene.control.Alert;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class SocioTorcedor extends javax.swing.JFrame {

    /**
     * Creates new form SocioTorcedor
     */
    public SocioTorcedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        lbl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btn02 = new javax.swing.JButton();
        tfParc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tp = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Seja Sócio Torcedor");

        jLabel2.setText("Ajude o São Paulo a ficar ainda maior");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha seu plano", "Sou Tricolor", "Vamos São Paulo", "Clube da Fé", "Tu és forte tu és grande" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        buttonGroup2.add(rb1);
        rb1.setText("Boleto à vista (20% de desconto)");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rb2);
        rb2.setSelected(true);
        rb2.setText("Cartão de Crédito");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rb3);
        rb3.setText("Cartão de Débito à vista (10% de desconto)");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        lbl.setToolTipText("");
        lbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblActionPerformed(evt);
            }
        });

        jLabel3.setText("Planos:");

        btn.setText("Finalizar");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        jLabel4.setText("Escolha forma de pagamento");

        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        jLabel5.setText("Ex: Mesal, Semestral ou Anual");

        btn02.setText("Cotar Plano");
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });

        tfParc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfParcActionPerformed(evt);
            }
        });

        jLabel6.setText("Em quantas vezes será parcelado?");

        jLabel7.setText("Min: 1 e Max: 8");

        tp.setColumns(20);
        tp.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        tp.setRows(5);
        jScrollPane3.setViewportView(tp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfParc, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rb3)
                                                    .addComponent(rb1))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(rb2)
                                                    .addGap(74, 74, 74))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 80, Short.MAX_VALUE))
                                            .addComponent(jScrollPane3)
                                            .addComponent(jScrollPane1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btn02)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(5, 5, 5)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfParc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb1))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn)
                    .addComponent(btn02))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
       
        
        
           if(comboBox.getSelectedItem().equals("Escolha seu plano")){
       
            JOptionPane.showMessageDialog(null, "Preencha Corretamente o campo plano",null,WIDTH);
               
       }
           else if(lbl.getText().equals("")){
               
           JOptionPane.showMessageDialog(null, "Preencha Corretamente formato do plano",null,WIDTH);
               
           }
           
           else if(lbl.getText().toLowerCase().equals("mensal")){
               
           JOptionPane.showMessageDialog(null, "Solicitação concluida",null,WIDTH);
               
           }
           
           else if(lbl.getText().toLowerCase().equals("semestral")){
               
           JOptionPane.showMessageDialog(null, "Solicitação concluida",null,WIDTH);
               
           }
           
           else if(lbl.getText().toLowerCase().equals("anual")){
               
           JOptionPane.showMessageDialog(null, "Solicitação concluida",null,WIDTH);
               
           }
           
           else{
              
               JOptionPane.showMessageDialog(null, "Preencha Corretamente formato do plano",null,WIDTH);
               
           }
       
    }//GEN-LAST:event_btnActionPerformed

    private void lblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed

            
           
       
    }//GEN-LAST:event_comboBoxActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        Double mensal;
        Double semestral;
        Double anual;
        
        if (comboBox.getSelectedItem().equals("Escolha seu plano")) {
            ta.setText(" ");
            tp.setText(" ");
        }
        if (comboBox.getSelectedItem().equals("Sou Tricolor")) {
            mensal = 12.00;
            semestral = 72.00;
            anual = 144.00;
         
            
            ta.setText(String.format(" Plano mensal: %.2f \n Plano semestral: "
                    + "%.2f \n Plano anual: %.2f",
                    mensal, semestral, anual));
             if (comboBox.getSelectedItem().equals("Sou Tricolor") && rb1.isSelected()) {
            
            ta.setText("");
                
            Double desconto = 0.2;    
                
            mensal = 12.00-(mensal*desconto);
            semestral = 72.00-(semestral*desconto);
            anual = 144.00-(anual*desconto);
         
            Double descM = 12.00*desconto;
            Double descS = 72.00*desconto;
            Double descA = 144.00*desconto;
            
            ta.setText(String.format(" Plano mensal: %.2f - desconto de %.2f reais\n Plano semestral: "
                    + "%.2f - desconto de %.2f reais\n Plano anual: %.2f - desconto de %.2f reais ",
                    mensal,descM, semestral,descS, anual,descA));
            
            }
            
            if (comboBox.getSelectedItem().equals("Sou Tricolor") && rb3.isSelected()) {
            
            ta.setText("");
                
            Double desconto = 0.1;    
                
            mensal = 12.00-(mensal*desconto);
            semestral = 72.00-(semestral*desconto);
            anual = 144.00-(anual*desconto);
         
            Double descM = 12.00*desconto;
            Double descS = 72.00*desconto;
            Double descA = 144.00*desconto;
            
            ta.setText(String.format(" Plano mensal: %.2f - desconto de %.2f reais\n Plano semestral: "
                    + "%.2f - desconto de %.2f reais\n Plano anual: %.2f - desconto de %.2f reais",
                    mensal,descM, semestral,descS, anual,descA));
            
            }
            
            String num1 = tfParc.getText();
                     
            Integer parcela = Integer.valueOf(num1);
            
            if ( parcela > 0 && parcela <=8 && rb2.isSelected()) {
                
                Double parcFinal1 = mensal/parcela;
                        
                Double parcFinal2 = semestral/parcela;
                                
                Double parcFinal3 = anual/parcela;
                
                tp.setText(String.format("Você irá pagar semestralmente %sX de: %.2f \n"
                        +"Você irá pagar anualmente %sX de: %.2f"
                        ,num1,parcFinal2,num1,parcFinal3));
            }else{
                tp.setText("Esta forma de pagamento \nnão permite parcelamento");
            }
            
        }
        
         if (comboBox.getSelectedItem().equals("Vamos São Paulo")) {
            mensal = 19.00;
            semestral = 114.00;
            anual = 228.00;
       
            ta.setText(String.format(" Plano mensal: %.2f \n Plano semestral: "
                    + "%.2f \n Plano anual: %.2f",
                    mensal, semestral, anual));
            
            
            if (comboBox.getSelectedItem().equals("Vamos São Paulo") && rb1.isSelected()) {
            
            Double desconto = 0.2;    
                
            mensal = 19.00-(mensal*desconto);
            semestral = 114.00-(semestral*desconto);
            anual = 228.00-(anual*desconto);
            
            Double descM = 19.00*desconto;
            Double descS = 114.00*desconto;
            Double descA = 228.00*desconto;
         
            
            ta.setText(String.format(" Plano mensal: %.2f - desconto de %.2f reais\n Plano semestral: "
                    + "%.2f - desconto de %.2f reais\n Plano anual: %.2f - desconto de %.2f reais",
                    mensal,descM, semestral,descS, anual,descA));
            
            }
            
            if (comboBox.getSelectedItem().equals("Vamos São Paulo") && rb3.isSelected()) {
            
            Double desconto = 0.1;    
                
            mensal = 19.00-(mensal*desconto);
            semestral = 114.00-(semestral*desconto);
            anual = 228.00-(anual*desconto);
            
            Double descM = 19.00*desconto;
            Double descS = 114.00*desconto;
            Double descA = 228.00*desconto;
         
            
            ta.setText(String.format(" Plano mensal: %.2f - desconto de %.2f reais\n Plano semestral: "
                    + "%.2f - desconto de %.2f reais\n Plano anual: %.2f - desconto de %.2f reais",
                    mensal,descM, semestral,descS, anual,descA));
            
            }
            
            String num1 = tfParc.getText();
                     
            Integer parcela = Integer.valueOf(num1);
            
            if ( parcela > 0 && parcela <=8 && rb2.isSelected()) {        
                Double parcFinal2 = semestral/parcela;
                                
                Double parcFinal3 = anual/parcela;
                
                tp.setText(String.format("Você irá pagar semestralmente %sX de: %.2f \n"
                        +"Você irá pagar anualmente %sX de: %.2f"
                        ,num1,parcFinal2,num1,parcFinal3));
            }else{
                tp.setText("Esta forma de pagamento \nnão permite parcelamento");
            }
            
        }
        if (comboBox.getSelectedItem().equals("Clube da Fé")) {
            mensal = 69.00;
            semestral = 414.00;
            anual = 828.00;
          
            
            ta.setText(String.format(" Plano mensal: %.2f \n Plano semestral: "
                    + "%.2f \n Plano anual: %.2f",
                    mensal, semestral, anual));
            
            if (comboBox.getSelectedItem().equals("Clube da Fé") && rb1.isSelected()) {
            
            Double desconto = 0.2;    
                
            mensal = 69.00-(mensal*desconto);
            semestral = 414.00-(semestral*desconto);
            anual = 828.00-(anual*desconto);
         
            Double descM = 69.00*desconto;
            Double descS = 414.00*desconto;
            Double descA = 828.00*desconto;
            
            ta.setText(String.format(" Plano mensal: %.2f - desconto de %.2f reais\n Plano semestral: "
                    + "%.2f - desconto de %.2f reais\n Plano anual: %.2f - desconto de %.2f reais",
                   mensal,descM, semestral,descS, anual,descA));
            
            }
            
            if (comboBox.getSelectedItem().equals("Clube da Fé") && rb3.isSelected()) {
            
            Double desconto = 0.1;    
                
            mensal = 69.00-(mensal*desconto);
            semestral = 414.00-(semestral*desconto);
            anual = 828.00-(anual*desconto);
         
            Double descM = 69.00*desconto;
            Double descS = 414.00*desconto;
            Double descA = 828.00*desconto;
            
            ta.setText(String.format(" Plano mensal: %.2f - desconto de %.2f reais\n Plano semestral: "
                    + "%.2f - desconto de %.2f reais\n Plano anual: %.2f - desconto de %.2f reais",
                    mensal,descM, semestral,descS, anual,descA));
            
            }
            
            String num1 = tfParc.getText();
                     
            Integer parcela = Integer.valueOf(num1);
            
            if ( parcela > 0 && parcela <=8 && rb2.isSelected()) {
                Double parcFinal2 = semestral/parcela;
                                
                Double parcFinal3 = anual/parcela;
                
                tp.setText(String.format("Você irá pagar semestralmente %sX de: %.2f \n"
                        +"Você irá pagar anualmente %sX de: %.2f"
                        ,num1,parcFinal2,num1,parcFinal3));
            }else{
                tp.setText("Esta forma de pagamento \nnão permite parcelamento");
            }
            
        }
        if (comboBox.getSelectedItem().equals("Tu és forte tu és grande")) {
            mensal = 100.00;
            semestral = 600.00;
            anual = 1200.00;
            
            
           ta.setText(String.format(" Plano mensal: %.2f \n Plano semestral: "
                    + "%.2f \n Plano anual: %.2f",
                    mensal, semestral,anual));
            
            if (comboBox.getSelectedItem().equals("Tu és forte tu és grande") && rb1.isSelected()) {
            
            Double desconto = 0.2;    
                
            mensal = 100.00-(mensal*desconto);
            semestral = 600.00-(semestral*desconto);
            anual = 1200.00-(anual*desconto);
         
            Double descM = 100.00*desconto;
            Double descS = 600.00*desconto;
            Double descA = 1200.00*desconto;
            
            ta.setText(String.format(" Plano mensal: %.2f - desconto de %.2f reais\n Plano semestral: "
                    + "%.2f - desconto de %.2f reais\n Plano anual: %.2f - desconto de %.2f reais",
                   mensal,descM, semestral,descS, anual,descA));
            
            }
            
            if (comboBox.getSelectedItem().equals("Tu és forte tu és grande") && rb3.isSelected()) {
            
            Double desconto = 0.1;    
                
            mensal = 100.00-(mensal*desconto);
            semestral = 600.00-(semestral*desconto);
            anual = 1200.00-(anual*desconto);
         
            Double descM = 100.00*desconto;
            Double descS = 600.00*desconto;
            Double descA = 1200.00*desconto;
            
            ta.setText(String.format(" Plano mensal: %.2f - desconto de %.2f reais\n Plano semestral: "
                    + "%.2f - desconto de %.2f reais\n Plano anual: %.2f - desconto de %.2f reais",
                    mensal,descM, semestral,descS, anual,descA));
            
            }
            
            String num1 = tfParc.getText();
                     
            Integer parcela = Integer.valueOf(num1);
            
            if ( parcela > 0 && parcela <=8 && rb2.isSelected()) {
                        
                Double parcFinal2 = semestral/parcela;
                                
                Double parcFinal3 = anual/parcela;
                
                tp.setText(String.format("Você irá pagar semestralmente %sX de: %.2f \n"
                        +"Você irá pagar anualmente %sX de: %.2f"
                        ,num1,parcFinal2,num1,parcFinal3));
            }else{
                tp.setText("Esta forma de pagamento \nnão permite parcelamento");
            }
           
        }
            
    }//GEN-LAST:event_btn02ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void tfParcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfParcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfParcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocioTorcedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocioTorcedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocioTorcedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocioTorcedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SocioTorcedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btn02;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lbl;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tfParc;
    private javax.swing.JTextArea tp;
    // End of variables declaration//GEN-END:variables
}
